regweb/src/main/java/it/arkproject/model/Demografica.java
package it.arkproject.model;

// Generated 5-nov-2014 12.09.28 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Min;
import javax.validation.constraints.Max;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Demografica generated by hbm2java
 */
@Entity
@Table(name = "demografica"
      , catalog = "regweb")
public class Demografica implements java.io.Serializable
{

   private Integer demograficaId;
   private Anagraficapaziente anagraficapaziente;
   private Assistenzaprivata assistenzaprivata;
   private Beneficiassistenziali beneficiassistenziali;
   private Conchivive conchivive;
   private Condizionieconomiche condizionieconomiche;
   private Contattisociali contattisociali;
   private Escepropriaabitazione escepropriaabitazione;
   private Livelloistruzione livelloistruzione;
   @NotNull(message = "Campo obbligatorio")
   private Statocivile statocivile;
   @NotNull(message = "Campo obbligatorio")
   @Min(value = 0, message = "Il valore deve essere compreso tra 0 e 15")
   @Max(value = 15, message = "Il valore deve essere compreso tra 0 e 15")
   private Integer numeroFigliViventi;
   private Integer utilizzoServizioPubblico;
   private Integer casaProprieta;
   private Integer anniUltimoTrasferimentoResidenza;
   private Integer presenzaBarriereArchitettoniche;
   private String medicoCurante;
   @NotNull(message="Campo obbligatorio")
   private Date dataCompilazione;

   public Demografica()
   {
   }

   public Demografica(Anagraficapaziente anagraficapaziente, Statocivile statocivile,Date dataCompilazione)
   {
      this.anagraficapaziente = anagraficapaziente;
      this.statocivile = statocivile;
      this.dataCompilazione = dataCompilazione;
   }

   public Demografica(Anagraficapaziente anagraficapaziente, Assistenzaprivata assistenzaprivata, Beneficiassistenziali beneficiassistenziali, Conchivive conchivive, Condizionieconomiche condizionieconomiche, Contattisociali contattisociali, Escepropriaabitazione escepropriaabitazione, Livelloistruzione livelloistruzione, Statocivile statocivile,Integer numeroFigliViventi, Integer utilizzoServizioPubblico, Integer casaProprieta, Integer anniUltimoTrasferimentoResidenza, Integer presenzaBarriereArchitettoniche, String medicoCurante,Date dataCompilazione)
   {
      this.anagraficapaziente = anagraficapaziente;
      this.assistenzaprivata = assistenzaprivata;
      this.beneficiassistenziali = beneficiassistenziali;
      this.conchivive = conchivive;
      this.condizionieconomiche = condizionieconomiche;
      this.contattisociali = contattisociali;
      this.escepropriaabitazione = escepropriaabitazione;
      this.livelloistruzione = livelloistruzione;
      this.statocivile = statocivile;
      this.numeroFigliViventi = numeroFigliViventi;
      this.utilizzoServizioPubblico = utilizzoServizioPubblico;
      this.casaProprieta = casaProprieta;
      this.anniUltimoTrasferimentoResidenza = anniUltimoTrasferimentoResidenza;
      this.presenzaBarriereArchitettoniche = presenzaBarriereArchitettoniche;
      this.medicoCurante = medicoCurante;
      this.dataCompilazione = dataCompilazione;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "demograficaID", unique = true, nullable = false)
   public Integer getDemograficaId()
   {
      return this.demograficaId;
   }

   public void setDemograficaId(Integer demograficaId)
   {
      this.demograficaId = demograficaId;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "anagraficapaziente_pazienteID", nullable = false)
   public Anagraficapaziente getAnagraficapaziente()
   {
      return this.anagraficapaziente;
   }

   public void setAnagraficapaziente(Anagraficapaziente anagraficapaziente)
   {
      this.anagraficapaziente = anagraficapaziente;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "assistenzaprivata_assistenzaPrivataID")
   public Assistenzaprivata getAssistenzaprivata()
   {
      return this.assistenzaprivata;
   }

   public void setAssistenzaprivata(Assistenzaprivata assistenzaprivata)
   {
      this.assistenzaprivata = assistenzaprivata;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "beneficiassistenziali_beneficiAssistenzialiID")
   public Beneficiassistenziali getBeneficiassistenziali()
   {
      return this.beneficiassistenziali;
   }

   public void setBeneficiassistenziali(Beneficiassistenziali beneficiassistenziali)
   {
      this.beneficiassistenziali = beneficiassistenziali;
   }

   @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
   @JoinColumn(name = "conchivive_conChiViveID")

   public Conchivive getConchivive()
   {
      return this.conchivive;
   }

   public void setConchivive(Conchivive conchivive)
   {
      this.conchivive = conchivive;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "condizioniEconomiche_condizioniEconomicheID")
   public Condizionieconomiche getCondizionieconomiche()
   {
      return this.condizionieconomiche;
   }

   public void setCondizionieconomiche(Condizionieconomiche condizionieconomiche)
   {
      this.condizionieconomiche = condizionieconomiche;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "contattisociali_contattiSocialiID")
   public Contattisociali getContattisociali()
   {
      return this.contattisociali;
   }

   public void setContattisociali(Contattisociali contattisociali)
   {
      this.contattisociali = contattisociali;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "escepropriaabitazione_escePropriaAbitazioneID")
   public Escepropriaabitazione getEscepropriaabitazione()
   {
      return this.escepropriaabitazione;
   }

   public void setEscepropriaabitazione(Escepropriaabitazione escepropriaabitazione)
   {
      this.escepropriaabitazione = escepropriaabitazione;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "livelloistruzione_livelloIstruzioneID")
   public Livelloistruzione getLivelloistruzione()
   {
      return this.livelloistruzione;
   }

   public void setLivelloistruzione(Livelloistruzione livelloistruzione)
   {
      this.livelloistruzione = livelloistruzione;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "statocivile_statoCivileID", nullable = false)
   public Statocivile getStatocivile()
   {
      return this.statocivile;
   }

   public void setStatocivile(Statocivile statocivile)
   {
      this.statocivile = statocivile;
   }

   @Column(name = "numeroFigliViventi")
   public Integer getNumeroFigliViventi()
   {
      return this.numeroFigliViventi;
   }

   public void setNumeroFigliViventi(Integer numeroFigliViventi)
   {
      this.numeroFigliViventi = numeroFigliViventi;
   }

   @Column(name = "utilizzoServizioPubblico")
   public Integer getUtilizzoServizioPubblico()
   {
      return this.utilizzoServizioPubblico;
   }

   public void setUtilizzoServizioPubblico(Integer utilizzoServizioPubblico)
   {
      this.utilizzoServizioPubblico = utilizzoServizioPubblico;
   }

   @Column(name = "casaProprieta")
   public Integer getCasaProprieta()
   {
      return this.casaProprieta;
   }

   public void setCasaProprieta(Integer casaProprieta)
   {
      this.casaProprieta = casaProprieta;
   }

   @Column(name = "anniUltimoTrasferimentoResidenza")
   public Integer getAnniUltimoTrasferimentoResidenza()
   {
      return this.anniUltimoTrasferimentoResidenza;
   }

   public void setAnniUltimoTrasferimentoResidenza(Integer anniUltimoTrasferimentoResidenza)
   {
      this.anniUltimoTrasferimentoResidenza = anniUltimoTrasferimentoResidenza;
   }

   @Column(name = "presenzaBarriereArchitettoniche")
   public Integer getPresenzaBarriereArchitettoniche()
   {
      return this.presenzaBarriereArchitettoniche;
   }

   public void setPresenzaBarriereArchitettoniche(Integer presenzaBarriereArchitettoniche)
   {
      this.presenzaBarriereArchitettoniche = presenzaBarriereArchitettoniche;
   }

   @Column(name = "medicoCurante", length = 45)
   public String getMedicoCurante()
   {
      return this.medicoCurante;
   }

   public void setMedicoCurante(String medicoCurante)
   {
      this.medicoCurante = medicoCurante;
   }
   @Temporal(TemporalType.DATE)
   @Column(name="dataCompilazione", nullable=false, length=10)
   public Date getDataCompilazione() {
       return this.dataCompilazione;
   }
   
   public void setDataCompilazione(Date dataCompilazione) {
       this.dataCompilazione = dataCompilazione;
   }
   
}

regweb/src/main/java/it/arkproject/view/DemograficaBean.java
package it.arkproject.view;

import it.arkproject.genericClass.AbstractBean;
import it.arkproject.model.Demografica;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.Stateful;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ConversationScoped
public class DemograficaBean extends AbstractBean<Demografica> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
  

	private List<SelectItem> itemYesNo;

	public List<SelectItem> getItemYesNo() {
		return itemYesNo;
	}

	public void setItemYesNo(List<SelectItem> itemYesNo) {
		this.itemYesNo = itemYesNo;
	}

	public List<SelectItem> fillItemYesNo() {
		itemYesNo = new ArrayList<>();
		itemYesNo.add(new SelectItem(-1,"-- Seleziona un elemento --" ));
		itemYesNo.add(new SelectItem(1, "Si"));
		itemYesNo.add(new SelectItem(0, "No"));
		return itemYesNo;
	}


}

regweb/src/main/java/it/arkproject/view/IstitutoBean.java
package it.arkproject.view;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Stateful;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.criteria.CriteriaQuery;

import it.arkproject.model.Istituto;

@Named
@Stateful
@SessionScoped
public class IstitutoBean implements Serializable
{
   private static final long serialVersionUID = 1L;

   private Istituto current;
   

   @PersistenceContext(unitName = "regWeb", type = PersistenceContextType.EXTENDED)
	private EntityManager entityManager;

	public List<Istituto> getAll() {
		CriteriaQuery<Istituto> criteria = this.entityManager
				.getCriteriaBuilder().createQuery(Istituto.class);
		return this.entityManager.createQuery(
				criteria.select(criteria.from(Istituto.class)))
				.getResultList();
	}
	
	public void  findById (Integer id){
		current = this.entityManager.find(Istituto.class, id);
	}

	public Istituto getCurrent() {
		return current;
	}

	public void setCurrent(Istituto current) {
		this.current = current;
	}
	

}

regweb/src/main/webapp/pages/secure/paziente/anagrafica/schede/demografica.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:o="http://omnifaces.org/ui" xmlns:p="http://primefaces.org/ui"
	template="/templates/patientDashboardTemplate.xhtml">


	<ui:define name="metadata">
		<f:metadata>
			<f:viewParam name="id" value='#{demograficaBean.id}' />
			<f:event type="preRenderView"
				listener='#{demograficaBean.retrieve()}' />
		</f:metadata>
	</ui:define>



	<ui:define name="dash">
		<div class="box-title">
			<h3>
				<i class="icon-list"></i>
				<c:choose>
					<c:when test='#{!empty demograficaBean.id}'>
				Modifica scheda demografica
			</c:when>
					<c:otherwise>
				Crea scheda demografica
			</c:otherwise>
				</c:choose>

			</h3>
		</div>
		<div class="box-content nopadding">
			<h:form id="demograficaForm" prependId="false"
				class='form-horizontal form-column form-bordered'>

				<div class="span6">
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Con chi vive:"
							for="conChiVive" />
						<div class="controls">
							<h:selectOneMenu id="conChiVive"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.conchivive}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{conchiviveBean.all}" var="_item"
									itemLabel="#{_item.descrizione}" itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgconChiVive" for="conChiVive"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Contatti sociali:"
							for="contattiSociali" />
						<div class="controls">
							<h:selectOneMenu id="contattiSociali"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.contattisociali}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{contattisocialiBean.all}" var="_item"
									itemLabel="#{_item.descrizione}" itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgcontattiSociali" for="contattiSociali"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Esce abitazione:"
							for="escePropriaAbitazione" />
						<div class="controls">
							<h:selectOneMenu id="escePropriaAbitazione"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.escepropriaabitazione}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{escepropriaabitazioneBean.all}"
									var="_item" itemLabel="#{_item.descrizione}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgescePropriaAbitazione"
								for="escePropriaAbitazione"
								errorClass="help-block alert alert-error" />
						</div>
					</div>
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Assistenza privata:"
							for="presenzaAssistenzaPrivata" />
						<div class="controls">
							<h:selectOneMenu id="presenzaAssistenzaPrivata"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.assistenzaprivata}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{assistenzaprivataBean.all}" var="_item"
									itemLabel="#{_item.descrizione}" itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgpresenzaAssistenzaPrivata"
								for="presenzaAssistenzaPrivata"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Anni dall'ultimo trasf.resid.:"
							for="anniUltimoTrasferimentoResidenza" />
						<div class="controls">
							<h:inputText id="anniUltimoTrasferimentoResidenza"
								class="input-large" maxlength="2"
								disabled="#{securityBean.isUser eq false}" autocomplete="off"
								value="#{demograficaBean.current.anniUltimoTrasferimentoResidenza}">
							</h:inputText>
							<h:message id="msganniUltimoTrasferimentoResidenza"
								for="anniUltimoTrasferimentoResidenza"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Presenza barriere architett.:"
							for="presenzaBarriereArchitettoniche" />
						<div class="controls">
							<h:selectOneMenu id="presenzaBarriereArchitettoniche"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.presenzaBarriereArchitettoniche}">
								<f:selectItems value="#{demograficaBean.fillItemYesNo()}"
									var="_item" itemLabel="#{_item.description}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgpresenzaBarriereArchitettoniche"
								for="presenzaBarriereArchitettoniche"
								errorClass="help-block alert alert-error" />
						</div>
					</div>


					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Livello di istruzione:" for="livelloIstruzione" />
						<div class="controls">
							<h:selectOneMenu id="livelloIstruzione"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.livelloistruzione}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{livelloistruzioneBean.all}" var="_item"
									itemLabel="#{_item.descrizione}" itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msglivelloIstruzione" for="livelloIstruzione"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Utilizzo di servizio pubblico:" for="servizioPubblico" />
						<div class="controls">
							<h:selectOneMenu id="servizioPubblico"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.utilizzoServizioPubblico}">
								<f:selectItems value="#{demograficaBean.fillItemYesNo()}"
									var="_item" itemLabel="#{_item.description}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgservizioPubblico" for="servizioPubblico"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

				</div>

				<div class="span6">

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Benefici assistenziali:" for="beneficiAssistenziali" />
						<div class="controls">
							<h:selectOneMenu id="beneficiAssistenziali"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.beneficiassistenziali}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{beneficiassistenzialiBean.all}"
									var="_item" itemLabel="#{_item.descrizione}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgbeneficiAssistenziali"
								for="beneficiAssistenziali"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label"
							value="Condizioni Economiche:"
							for="condizioniEconomichecondizioniEconomicheID" />
						<div class="controls">
							<h:selectOneMenu id="condizioniEconomichecondizioniEconomicheID"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.condizionieconomiche}">
								<f:selectItem itemLabel="-- Selezione un elemento --"
									noSelectionOption="true" />
								<f:selectItems value="#{condizionieconomicheBean.all}"
									var="_item" itemLabel="#{_item.descrizione}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgcondizioniEconomichecondizioniEconomicheID"
								for="condizioniEconomichecondizioniEconomicheID"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Casa di proprietà:"
							for="casaProprieta" />
						<div class="controls">
							<h:selectOneMenu id="casaProprieta"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.casaProprieta}">
								<f:selectItems value="#{demograficaBean.fillItemYesNo()}"
									var="_item" itemLabel="#{_item.description}"
									itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgcasaProprieta" for="casaProprieta"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Medico curante:"
							for="medicoCurante" />
						<div class="controls">
							<h:inputText id="medicoCurante" class="input-large"
								maxlength="45" disabled="#{securityBean.isUser eq false}"
								autocomplete="off"
								value="#{demograficaBean.current.medicoCurante}">
							</h:inputText>
							<h:message id="msgmedicoCurante" for="medicoCurante"
								errorClass="help-block alert alert-error" />
						</div>
					</div>
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Stato civile: *"
							for="statoCivile" />
						<div class="controls">
							<h:selectOneMenu id="statoCivile"
								converter="omnifaces.SelectItemsConverter"
								disabled="#{securityBean.isUser eq false}"
								value="#{demograficaBean.current.statocivile}">
								<f:selectItem itemLabel="-- Selezione un elemento --" noSelectionOption="true" />
								<f:selectItems value="#{statocivileBean.all}" var="_item"
									itemLabel="#{_item.descrizione}" itemValue="#{_item}" />
							</h:selectOneMenu>
							<h:message id="msgstatoCivile" for="statoCivile"
								errorClass="help-block alert alert-error" />
						</div>
					</div>
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Numero figli viventi:"
							for="numeroFigliViventi" />
						<div class="controls">
							<h:inputText id="numeroFigliViventi" class="input-large"
								maxlength="2" disabled="#{securityBean.isUser eq false}"
								autocomplete="off"
								value="#{demograficaBean.current.numeroFigliViventi}">
							</h:inputText>
							<h:message id="msgnumeroFigliViventi" for="numeroFigliViventi"
								errorClass="help-block alert alert-error" />
						</div>
					</div>
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="Data di compilazione:"
							for="dataCompilazioneTwoColumn" />
						<div class="controls"  >
							<p:calendar id="dataCompilazioneTwoColumn" styleClass="input-xlarge"
								validator="#{demograficaBean.validateDate}"
								disabled="#{securityBean.isUserAdmin eq false}"
								autocomplete="off"
								value="#{demograficaBean.current.dataCompilazione}"
								pattern="dd/MM/yyyy" title="Data di compilazione" />
							<p:message id="msgdataCompilazioneTwoColumn" for="dataCompilazioneTwoColumn" />
						</div>
					</div>
					<div class="control-group twoColumn">
						<h:outputLabel class="control-label" value="" for="empy" />
						<div class="controls">
							<h:inputText id="empy" class="input-large" disabled="true"
								autocomplete="off" value="">
							</h:inputText>
							<h:message id="msgempy" for="empy"
								errorClass="help-block alert alert-error" />
						</div>
					</div>

				</div>
				<div class="span12">
					<div class="form-actions">
						<h:commandLink value="#{bundle.IndirizzoresidenzaSaveLink}"
							rendered="#{securityBean.isUser eq true}"
							action='#{demograficaBean.update()}' styleClass="btn btn-primary">
						</h:commandLink>

						<h:link value="Annulla"
							outcome="/pages/secure/paziente/patientDashboard"
							styleClass="btn">
							<f:param name="cid" value="#{demograficaBean.conversation.id}" />
						</h:link>

					</div>
				</div>



			</h:form>
		</div>
	</ui:define>
</ui:composition>